//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.3053 版自动生成。
// 
namespace MobileBaseDLL.WebServerBarCode {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DBWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class DBWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public DBWebService() {
            this.Url = "http://localhost/webTT/DBService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b登陆", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool b登陆(string sUid, string sPwd) {
            object[] results = this.Invoke("b登陆", new object[] {
                        sUid,
                        sPwd});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginb登陆(string sUid, string sPwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("b登陆", new object[] {
                        sUid,
                        sPwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool Endb登陆(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/s登陆", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string s登陆(string sUid) {
            object[] results = this.Invoke("s登陆", new object[] {
                        sUid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begins登陆(string sUid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("s登陆", new object[] {
                        sUid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Ends登陆(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dtm当前服务器时间", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime dtm当前服务器时间() {
            object[] results = this.Invoke("dtm当前服务器时间", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindtm当前服务器时间(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dtm当前服务器时间", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.DateTime Enddtm当前服务器时间(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt存货信息", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt存货信息(string sInvCode) {
            object[] results = this.Invoke("dt存货信息", new object[] {
                        sInvCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindt存货信息(string sInvCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dt存货信息", new object[] {
                        sInvCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddt存货信息(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/s货仓", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string s货仓(string sWhCode) {
            object[] results = this.Invoke("s货仓", new object[] {
                        sWhCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begins货仓(string sWhCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("s货仓", new object[] {
                        sWhCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Ends货仓(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/s货位", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string s货位(string sWhCode) {
            object[] results = this.Invoke("s货位", new object[] {
                        sWhCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begins货位(string sWhCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("s货位", new object[] {
                        sWhCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Ends货位(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/s仓库", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string s仓库(string sWhCode) {
            object[] results = this.Invoke("s仓库", new object[] {
                        sWhCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begins仓库(string sWhCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("s仓库", new object[] {
                        sWhCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Ends仓库(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/d货位现存量", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal d货位现存量(string sInvCode, string sBatch, string sFree1, string sFree2, string sFree3, string sFree4, string sWhPos) {
            object[] results = this.Invoke("d货位现存量", new object[] {
                        sInvCode,
                        sBatch,
                        sFree1,
                        sFree2,
                        sFree3,
                        sFree4,
                        sWhPos});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begind货位现存量(string sInvCode, string sBatch, string sFree1, string sFree2, string sFree3, string sFree4, string sWhPos, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("d货位现存量", new object[] {
                        sInvCode,
                        sBatch,
                        sFree1,
                        sFree2,
                        sFree3,
                        sFree4,
                        sWhPos}, callback, asyncState);
        }
        
        /// <remarks/>
        public decimal Endd货位现存量(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/d仓库现存量", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal d仓库现存量(string sInvCode, string sBatch, string sFree1, string sFree2, string sFree3, string sFree4, string sWhCode) {
            object[] results = this.Invoke("d仓库现存量", new object[] {
                        sInvCode,
                        sBatch,
                        sFree1,
                        sFree2,
                        sFree3,
                        sFree4,
                        sWhCode});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begind仓库现存量(string sInvCode, string sBatch, string sFree1, string sFree2, string sFree3, string sFree4, string sWhCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("d仓库现存量", new object[] {
                        sInvCode,
                        sBatch,
                        sFree1,
                        sFree2,
                        sFree3,
                        sFree4,
                        sWhCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public decimal Endd仓库现存量(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Chk货位是否存在", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Chk货位是否存在(string sBarCode) {
            object[] results = this.Invoke("Chk货位是否存在", new object[] {
                        sBarCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChk货位是否存在(string sBarCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Chk货位是否存在", new object[] {
                        sBarCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndChk货位是否存在(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Chk采购入库条码是否已经使用", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Chk采购入库条码是否已经使用(string sBarCode) {
            object[] results = this.Invoke("Chk采购入库条码是否已经使用", new object[] {
                        sBarCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChk采购入库条码是否已经使用(string sBarCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Chk采购入库条码是否已经使用", new object[] {
                        sBarCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndChk采购入库条码是否已经使用(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Save采购入库单", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Save采购入库单(System.Data.DataTable dt) {
            object[] results = this.Invoke("Save采购入库单", new object[] {
                        dt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSave采购入库单(System.Data.DataTable dt, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Save采购入库单", new object[] {
                        dt}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSave采购入库单(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt采购条码信息", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt采购条码信息(string sBarCode, string sCode) {
            object[] results = this.Invoke("dt采购条码信息", new object[] {
                        sBarCode,
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindt采购条码信息(string sBarCode, string sCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dt采购条码信息", new object[] {
                        sBarCode,
                        sCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddt采购条码信息(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt到货单信息", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt到货单信息(string sCode) {
            object[] results = this.Invoke("dt到货单信息", new object[] {
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindt到货单信息(string sCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dt到货单信息", new object[] {
                        sCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddt到货单信息(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt到货单明细信息", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt到货单明细信息(string sCode, string sWhere) {
            object[] results = this.Invoke("dt到货单明细信息", new object[] {
                        sCode,
                        sWhere});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindt到货单明细信息(string sCode, string sWhere, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dt到货单明细信息", new object[] {
                        sCode,
                        sWhere}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddt到货单明细信息(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt到货单明细信息2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt到货单明细信息2(string sCode, string sWhere) {
            object[] results = this.Invoke("dt到货单明细信息2", new object[] {
                        sCode,
                        sWhere});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindt到货单明细信息2(string sCode, string sWhere, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dt到货单明细信息2", new object[] {
                        sCode,
                        sWhere}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddt到货单明细信息2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt采购订单信息", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt采购订单信息(string sCode) {
            object[] results = this.Invoke("dt采购订单信息", new object[] {
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindt采购订单信息(string sCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dt采购订单信息", new object[] {
                        sCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddt采购订单信息(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt生产订单信息", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt生产订单信息(string sCode, string sRowNo) {
            object[] results = this.Invoke("dt生产订单信息", new object[] {
                        sCode,
                        sRowNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindt生产订单信息(string sCode, string sRowNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dt生产订单信息", new object[] {
                        sCode,
                        sRowNo}, callback, asyncState);
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt生产订单子件未出库信息", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt生产订单子件未出库信息(string sCode, string sRowNo)
        {
            object[] results = this.Invoke("dt生产订单子件未出库信息", new object[] {
                        sCode,
                        sRowNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public string Enddt生产订单信息(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt生产订单子件信息", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt生产订单子件信息(string sCode, string sRowNo, string sInvcode) {
            object[] results = this.Invoke("dt生产订单子件信息", new object[] {
                        sCode,
                        sRowNo,
                        sInvcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindt生产订单子件信息(string sCode, string sRowNo, string sInvcode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dt生产订单子件信息", new object[] {
                        sCode,
                        sRowNo,
                        sInvcode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddt生产订单子件信息(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt材料出库条码信息", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt材料出库条码信息(string sBarCode, string sCode, string sRowNO) {
            object[] results = this.Invoke("dt材料出库条码信息", new object[] {
                        sBarCode,
                        sCode,
                        sRowNO});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindt材料出库条码信息(string sBarCode, string sCode, string sRowNO, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dt材料出库条码信息", new object[] {
                        sBarCode,
                        sCode,
                        sRowNO}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddt材料出库条码信息(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Chk材料出库条码是否已经使用", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Chk材料出库条码是否已经使用(string sBarCode) {
            object[] results = this.Invoke("Chk材料出库条码是否已经使用", new object[] {
                        sBarCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChk材料出库条码是否已经使用(string sBarCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Chk材料出库条码是否已经使用", new object[] {
                        sBarCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndChk材料出库条码是否已经使用(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Save材料出库单", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Save材料出库单(System.Data.DataTable dt, string iRowNo) {
            object[] results = this.Invoke("Save材料出库单", new object[] {
                        dt,
                        iRowNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSave材料出库单(System.Data.DataTable dt, string iRowNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Save材料出库单", new object[] {
                        dt,
                        iRowNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSave材料出库单(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Save产品入库单", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Save产品入库单(System.Data.DataTable dt) {
            object[] results = this.Invoke("Save产品入库单", new object[] {
                        dt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSave产品入库单(System.Data.DataTable dt, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Save产品入库单", new object[] {
                        dt}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSave产品入库单(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Chk产品入库条码是否已经使用", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Chk产品入库条码是否已经使用(string sBarCode) {
            object[] results = this.Invoke("Chk产品入库条码是否已经使用", new object[] {
                        sBarCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChk产品入库条码是否已经使用(string sBarCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Chk产品入库条码是否已经使用", new object[] {
                        sBarCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndChk产品入库条码是否已经使用(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt产品入库条码信息", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt产品入库条码信息(string sBarCode) {
            object[] results = this.Invoke("dt产品入库条码信息", new object[] {
                        sBarCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindt产品入库条码信息(string sBarCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dt产品入库条码信息", new object[] {
                        sBarCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddt产品入库条码信息(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Chk销售出库条码是否已经使用", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Chk销售出库条码是否已经使用(string sBarCode) {
            object[] results = this.Invoke("Chk销售出库条码是否已经使用", new object[] {
                        sBarCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChk销售出库条码是否已经使用(string sBarCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Chk销售出库条码是否已经使用", new object[] {
                        sBarCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndChk销售出库条码是否已经使用(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt销售出库条码信息", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt销售出库条码信息(string sBarCode, string sCode) {
            object[] results = this.Invoke("dt销售出库条码信息", new object[] {
                        sBarCode,
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindt销售出库条码信息(string sBarCode, string sCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dt销售出库条码信息", new object[] {
                        sBarCode,
                        sCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddt销售出库条码信息(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt销售订单信息", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt销售订单信息(string sCode) {
            object[] results = this.Invoke("dt销售订单信息", new object[] {
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindt销售订单信息(string sCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dt销售订单信息", new object[] {
                        sCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddt销售订单信息(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt销售订单明细信息", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt销售订单明细信息(string sCode, string sWhere) {
            object[] results = this.Invoke("dt销售订单明细信息", new object[] {
                        sCode,
                        sWhere});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindt销售订单明细信息(string sCode, string sWhere, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dt销售订单明细信息", new object[] {
                        sCode,
                        sWhere}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddt销售订单明细信息(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Save销售出库单", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Save销售出库单(System.Data.DataTable dt) {
            object[] results = this.Invoke("Save销售出库单", new object[] {
                        dt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSave销售出库单(System.Data.DataTable dt, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Save销售出库单", new object[] {
                        dt}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSave销售出库单(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt发货单信息", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt发货单信息(string sCode) {
            object[] results = this.Invoke("dt发货单信息", new object[] {
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindt发货单信息(string sCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dt发货单信息", new object[] {
                        sCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddt发货单信息(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt盘点单信息", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt盘点单信息(string sCode) {
            object[] results = this.Invoke("dt盘点单信息", new object[] {
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindt盘点单信息(string sCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dt盘点单信息", new object[] {
                        sCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddt盘点单信息(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt盘点条码信息", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt盘点条码信息(string sBarCode, string sCode) {
            object[] results = this.Invoke("dt盘点条码信息", new object[] {
                        sBarCode,
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindt盘点条码信息(string sBarCode, string sCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dt盘点条码信息", new object[] {
                        sBarCode,
                        sCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddt盘点条码信息(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Save盘点数据", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Save盘点数据(System.Data.DataTable dt, string sCode) {
            object[] results = this.Invoke("Save盘点数据", new object[] {
                        dt,
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSave盘点数据(System.Data.DataTable dt, string sCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Save盘点数据", new object[] {
                        dt,
                        sCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSave盘点数据(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Save货位调整单", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Save货位调整单(System.Data.DataTable dt) {
            object[] results = this.Invoke("Save货位调整单", new object[] {
                        dt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSave货位调整单(System.Data.DataTable dt, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Save货位调整单", new object[] {
                        dt}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSave货位调整单(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt存货条码信息", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt存货条码信息(string sBarCode) {
            object[] results = this.Invoke("dt存货条码信息", new object[] {
                        sBarCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindt存货条码信息(string sBarCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dt存货条码信息", new object[] {
                        sBarCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddt存货条码信息(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
