//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5420
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.5420 版自动生成。
// 
#pragma warning disable 1591

namespace UseWebService.WebServiceQCDQ {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DBWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class DBWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback sRdrecord09_SaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback sRdrecord10_SaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback sRdrecord01_AuditOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DBWebService() {
            this.Url = global::UseWebService.Properties.Settings.Default.UseWebService_WebServiceQCDQ_DBWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event sRdrecord09_SaveCompletedEventHandler sRdrecord09_SaveCompleted;
        
        /// <remarks/>
        public event sRdrecord10_SaveCompletedEventHandler sRdrecord10_SaveCompleted;
        
        /// <remarks/>
        public event sRdrecord01_AuditCompletedEventHandler sRdrecord01_AuditCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sRdrecord09_Save", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sRdrecord09_Save(string sWhCode, string sRdCode, string sDepCode, string sCreater, string sDate, string sInvCode, string sBatch, string sQty) {
            object[] results = this.Invoke("sRdrecord09_Save", new object[] {
                        sWhCode,
                        sRdCode,
                        sDepCode,
                        sCreater,
                        sDate,
                        sInvCode,
                        sBatch,
                        sQty});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sRdrecord09_SaveAsync(string sWhCode, string sRdCode, string sDepCode, string sCreater, string sDate, string sInvCode, string sBatch, string sQty) {
            this.sRdrecord09_SaveAsync(sWhCode, sRdCode, sDepCode, sCreater, sDate, sInvCode, sBatch, sQty, null);
        }
        
        /// <remarks/>
        public void sRdrecord09_SaveAsync(string sWhCode, string sRdCode, string sDepCode, string sCreater, string sDate, string sInvCode, string sBatch, string sQty, object userState) {
            if ((this.sRdrecord09_SaveOperationCompleted == null)) {
                this.sRdrecord09_SaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsRdrecord09_SaveOperationCompleted);
            }
            this.InvokeAsync("sRdrecord09_Save", new object[] {
                        sWhCode,
                        sRdCode,
                        sDepCode,
                        sCreater,
                        sDate,
                        sInvCode,
                        sBatch,
                        sQty}, this.sRdrecord09_SaveOperationCompleted, userState);
        }
        
        private void OnsRdrecord09_SaveOperationCompleted(object arg) {
            if ((this.sRdrecord09_SaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sRdrecord09_SaveCompleted(this, new sRdrecord09_SaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sRdrecord10_Save", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sRdrecord10_Save(string sWOCode, string sZJCode, string sWhCode, string sRdCode, string sDepCode, string sCreater, string sDate, string sInvCode, string sBatch, string sQty) {
            object[] results = this.Invoke("sRdrecord10_Save", new object[] {
                        sWOCode,
                        sZJCode,
                        sWhCode,
                        sRdCode,
                        sDepCode,
                        sCreater,
                        sDate,
                        sInvCode,
                        sBatch,
                        sQty});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sRdrecord10_SaveAsync(string sWOCode, string sZJCode, string sWhCode, string sRdCode, string sDepCode, string sCreater, string sDate, string sInvCode, string sBatch, string sQty) {
            this.sRdrecord10_SaveAsync(sWOCode, sZJCode, sWhCode, sRdCode, sDepCode, sCreater, sDate, sInvCode, sBatch, sQty, null);
        }
        
        /// <remarks/>
        public void sRdrecord10_SaveAsync(string sWOCode, string sZJCode, string sWhCode, string sRdCode, string sDepCode, string sCreater, string sDate, string sInvCode, string sBatch, string sQty, object userState) {
            if ((this.sRdrecord10_SaveOperationCompleted == null)) {
                this.sRdrecord10_SaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsRdrecord10_SaveOperationCompleted);
            }
            this.InvokeAsync("sRdrecord10_Save", new object[] {
                        sWOCode,
                        sZJCode,
                        sWhCode,
                        sRdCode,
                        sDepCode,
                        sCreater,
                        sDate,
                        sInvCode,
                        sBatch,
                        sQty}, this.sRdrecord10_SaveOperationCompleted, userState);
        }
        
        private void OnsRdrecord10_SaveOperationCompleted(object arg) {
            if ((this.sRdrecord10_SaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sRdrecord10_SaveCompleted(this, new sRdrecord10_SaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sRdrecord01_Audit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sRdrecord01_Audit(string sCode, string sAuditer, string sDate) {
            object[] results = this.Invoke("sRdrecord01_Audit", new object[] {
                        sCode,
                        sAuditer,
                        sDate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sRdrecord01_AuditAsync(string sCode, string sAuditer, string sDate) {
            this.sRdrecord01_AuditAsync(sCode, sAuditer, sDate, null);
        }
        
        /// <remarks/>
        public void sRdrecord01_AuditAsync(string sCode, string sAuditer, string sDate, object userState) {
            if ((this.sRdrecord01_AuditOperationCompleted == null)) {
                this.sRdrecord01_AuditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsRdrecord01_AuditOperationCompleted);
            }
            this.InvokeAsync("sRdrecord01_Audit", new object[] {
                        sCode,
                        sAuditer,
                        sDate}, this.sRdrecord01_AuditOperationCompleted, userState);
        }
        
        private void OnsRdrecord01_AuditOperationCompleted(object arg) {
            if ((this.sRdrecord01_AuditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sRdrecord01_AuditCompleted(this, new sRdrecord01_AuditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void sRdrecord09_SaveCompletedEventHandler(object sender, sRdrecord09_SaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sRdrecord09_SaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sRdrecord09_SaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void sRdrecord10_SaveCompletedEventHandler(object sender, sRdrecord10_SaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sRdrecord10_SaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sRdrecord10_SaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void sRdrecord01_AuditCompletedEventHandler(object sender, sRdrecord01_AuditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sRdrecord01_AuditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sRdrecord01_AuditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591