//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.5485 版自动生成。
// 
namespace TH.Smart.WebService.WebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsBarCodeSoap", Namespace="http://tempuri.org/")]
    public partial class WsBarCode : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WsBarCode() {
            this.Url = "http://192.168.150.1/webDMC/DBScanForCheck.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sServerTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sServerTime() {
            object[] results = this.Invoke("sServerTime", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsServerTime(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sServerTime", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsServerTime(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sCheckRight", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sCheckRight(string sFormID, string sUserid) {
            object[] results = this.Invoke("sCheckRight", new object[] {
                        sFormID,
                        sUserid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsCheckRight(string sFormID, string sUserid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sCheckRight", new object[] {
                        sFormID,
                        sUserid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsCheckRight(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sLogin(string sUid, string sPwd) {
            object[] results = this.Invoke("sLogin", new object[] {
                        sUid,
                        sPwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsLogin(string sUid, string sPwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sLogin", new object[] {
                        sUid,
                        sPwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsLogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sUpdatePwd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sUpdatePwd(string sUid, string sPwd, string sOldPwd) {
            object[] results = this.Invoke("sUpdatePwd", new object[] {
                        sUid,
                        sPwd,
                        sOldPwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsUpdatePwd(string sUid, string sPwd, string sOldPwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sUpdatePwd", new object[] {
                        sUid,
                        sPwd,
                        sOldPwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsUpdatePwd(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dtRdCodeScan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dtRdCodeScan(string sBarCode) {
            object[] results = this.Invoke("dtRdCodeScan", new object[] {
                        sBarCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindtRdCodeScan(string sBarCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dtRdCodeScan", new object[] {
                        sBarCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EnddtRdCodeScan(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dtScanBarCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dtScanBarCode(string sBarCode) {
            object[] results = this.Invoke("dtScanBarCode", new object[] {
                        sBarCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindtScanBarCode(string sBarCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dtScanBarCode", new object[] {
                        sBarCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EnddtScanBarCode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/iChkBarCodeUsed", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int iChkBarCodeUsed(string sType, string sCode, string BarCode, int RDType) {
            object[] results = this.Invoke("iChkBarCodeUsed", new object[] {
                        sType,
                        sCode,
                        BarCode,
                        RDType});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginiChkBarCodeUsed(string sType, string sCode, string BarCode, int RDType, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("iChkBarCodeUsed", new object[] {
                        sType,
                        sCode,
                        BarCode,
                        RDType}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndiChkBarCodeUsed(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/iBarCodeUsed", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int iBarCodeUsed(string sBarCode, string sType) {
            object[] results = this.Invoke("iBarCodeUsed", new object[] {
                        sBarCode,
                        sType});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginiBarCodeUsed(string sBarCode, string sType, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("iBarCodeUsed", new object[] {
                        sBarCode,
                        sType}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndiBarCodeUsed(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dBarCodeQty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal dBarCodeQty(string sBarCode) {
            object[] results = this.Invoke("dBarCodeQty", new object[] {
                        sBarCode});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindBarCodeQty(string sBarCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dBarCodeQty", new object[] {
                        sBarCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public decimal EnddBarCodeQty(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sBarCodeInvalid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sBarCodeInvalid(System.Data.DataTable dt) {
            object[] results = this.Invoke("sBarCodeInvalid", new object[] {
                        dt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsBarCodeInvalid(System.Data.DataTable dt, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sBarCodeInvalid", new object[] {
                        dt}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsBarCodeInvalid(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sRdrecord01", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sRdrecord01(string sCode) {
            object[] results = this.Invoke("sRdrecord01", new object[] {
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsRdrecord01(string sCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sRdrecord01", new object[] {
                        sCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsRdrecord01(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sSaveRdrecord01ChkQty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sSaveRdrecord01ChkQty(string sCode, System.Data.DataTable dtBarCode, string sUid) {
            object[] results = this.Invoke("sSaveRdrecord01ChkQty", new object[] {
                        sCode,
                        dtBarCode,
                        sUid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsSaveRdrecord01ChkQty(string sCode, System.Data.DataTable dtBarCode, string sUid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sSaveRdrecord01ChkQty", new object[] {
                        sCode,
                        dtBarCode,
                        sUid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsSaveRdrecord01ChkQty(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sRdrecord09", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sRdrecord09(string sCode) {
            object[] results = this.Invoke("sRdrecord09", new object[] {
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsRdrecord09(string sCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sRdrecord09", new object[] {
                        sCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsRdrecord09(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sSaveRdrecord09ChkQty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sSaveRdrecord09ChkQty(string sCode, System.Data.DataTable dtBarCode, string sUid) {
            object[] results = this.Invoke("sSaveRdrecord09ChkQty", new object[] {
                        sCode,
                        dtBarCode,
                        sUid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsSaveRdrecord09ChkQty(string sCode, System.Data.DataTable dtBarCode, string sUid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sSaveRdrecord09ChkQty", new object[] {
                        sCode,
                        dtBarCode,
                        sUid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsSaveRdrecord09ChkQty(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sRdrecord08", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sRdrecord08(string sCode) {
            object[] results = this.Invoke("sRdrecord08", new object[] {
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsRdrecord08(string sCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sRdrecord08", new object[] {
                        sCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsRdrecord08(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sSaveRdrecord08ChkQty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sSaveRdrecord08ChkQty(string sCode, System.Data.DataTable dtBarCode, string sUid) {
            object[] results = this.Invoke("sSaveRdrecord08ChkQty", new object[] {
                        sCode,
                        dtBarCode,
                        sUid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsSaveRdrecord08ChkQty(string sCode, System.Data.DataTable dtBarCode, string sUid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sSaveRdrecord08ChkQty", new object[] {
                        sCode,
                        dtBarCode,
                        sUid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsSaveRdrecord08ChkQty(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sRdrecord11", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sRdrecord11(string sCode) {
            object[] results = this.Invoke("sRdrecord11", new object[] {
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsRdrecord11(string sCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sRdrecord11", new object[] {
                        sCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsRdrecord11(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sSaveRdrecord11ChkQty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sSaveRdrecord11ChkQty(string sCode, System.Data.DataTable dtBarCode, string sUid) {
            object[] results = this.Invoke("sSaveRdrecord11ChkQty", new object[] {
                        sCode,
                        dtBarCode,
                        sUid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsSaveRdrecord11ChkQty(string sCode, System.Data.DataTable dtBarCode, string sUid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sSaveRdrecord11ChkQty", new object[] {
                        sCode,
                        dtBarCode,
                        sUid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsSaveRdrecord11ChkQty(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sTransVouch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sTransVouch(string sCode) {
            object[] results = this.Invoke("sTransVouch", new object[] {
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsTransVouch(string sCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sTransVouch", new object[] {
                        sCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsTransVouch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sSaveTransVouchChkQty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sSaveTransVouchChkQty(string sCode, System.Data.DataTable dtBarCode, string sUid) {
            object[] results = this.Invoke("sSaveTransVouchChkQty", new object[] {
                        sCode,
                        dtBarCode,
                        sUid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsSaveTransVouchChkQty(string sCode, System.Data.DataTable dtBarCode, string sUid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sSaveTransVouchChkQty", new object[] {
                        sCode,
                        dtBarCode,
                        sUid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsSaveTransVouchChkQty(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sCheckVouch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sCheckVouch(string sCode) {
            object[] results = this.Invoke("sCheckVouch", new object[] {
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsCheckVouch(string sCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sCheckVouch", new object[] {
                        sCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsCheckVouch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sSaveCheckVouchChkQty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sSaveCheckVouchChkQty(string sCode, System.Data.DataTable dtBarCode) {
            object[] results = this.Invoke("sSaveCheckVouchChkQty", new object[] {
                        sCode,
                        dtBarCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsSaveCheckVouchChkQty(string sCode, System.Data.DataTable dtBarCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sSaveCheckVouchChkQty", new object[] {
                        sCode,
                        dtBarCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsSaveCheckVouchChkQty(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sSaveBox", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sSaveBox(string sCode, System.Data.DataTable dtBarCode) {
            object[] results = this.Invoke("sSaveBox", new object[] {
                        sCode,
                        dtBarCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsSaveBox(string sCode, System.Data.DataTable dtBarCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sSaveBox", new object[] {
                        sCode,
                        dtBarCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsSaveBox(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sSaveUnBox", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sSaveUnBox(string sCode) {
            object[] results = this.Invoke("sSaveUnBox", new object[] {
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsSaveUnBox(string sCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sSaveUnBox", new object[] {
                        sCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsSaveUnBox(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dtSBoxBarCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dtSBoxBarCode(string sBarCode) {
            object[] results = this.Invoke("dtSBoxBarCode", new object[] {
                        sBarCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindtSBoxBarCode(string sBarCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dtSBoxBarCode", new object[] {
                        sBarCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EnddtSBoxBarCode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dtSBoxInvCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dtSBoxInvCode(string sBarCode) {
            object[] results = this.Invoke("dtSBoxInvCode", new object[] {
                        sBarCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindtSBoxInvCode(string sBarCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dtSBoxInvCode", new object[] {
                        sBarCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EnddtSBoxInvCode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sRdrecord10", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sRdrecord10(string sCode) {
            object[] results = this.Invoke("sRdrecord10", new object[] {
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsRdrecord10(string sCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sRdrecord10", new object[] {
                        sCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsRdrecord10(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sSaveRdrecord10ChkQty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sSaveRdrecord10ChkQty(string sCode, System.Data.DataTable dtBarCode, string sUid) {
            object[] results = this.Invoke("sSaveRdrecord10ChkQty", new object[] {
                        sCode,
                        dtBarCode,
                        sUid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsSaveRdrecord10ChkQty(string sCode, System.Data.DataTable dtBarCode, string sUid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sSaveRdrecord10ChkQty", new object[] {
                        sCode,
                        dtBarCode,
                        sUid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsSaveRdrecord10ChkQty(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sDispatchList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sDispatchList(string sCode) {
            object[] results = this.Invoke("sDispatchList", new object[] {
                        sCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsDispatchList(string sCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sDispatchList", new object[] {
                        sCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsDispatchList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sSaveDispatchListChkQty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sSaveDispatchListChkQty(string sCode, System.Data.DataTable dtBarCode, string sUid) {
            object[] results = this.Invoke("sSaveDispatchListChkQty", new object[] {
                        sCode,
                        dtBarCode,
                        sUid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsSaveDispatchListChkQty(string sCode, System.Data.DataTable dtBarCode, string sUid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sSaveDispatchListChkQty", new object[] {
                        sCode,
                        dtBarCode,
                        sUid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsSaveDispatchListChkQty(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sOMRdrecord01", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sOMRdrecord01(string sCode, string sInvCode) {
            object[] results = this.Invoke("sOMRdrecord01", new object[] {
                        sCode,
                        sInvCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsOMRdrecord01(string sCode, string sInvCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sOMRdrecord01", new object[] {
                        sCode,
                        sInvCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsOMRdrecord01(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sSaveBarCodeAdjust", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sSaveBarCodeAdjust(string sBarCode, decimal dQty, decimal dQtyUse, string CreateUid) {
            object[] results = this.Invoke("sSaveBarCodeAdjust", new object[] {
                        sBarCode,
                        dQty,
                        dQtyUse,
                        CreateUid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsSaveBarCodeAdjust(string sBarCode, decimal dQty, decimal dQtyUse, string CreateUid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sSaveBarCodeAdjust", new object[] {
                        sBarCode,
                        dQty,
                        dQtyUse,
                        CreateUid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsSaveBarCodeAdjust(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrintBarCodeAdjust", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PrintBarCodeAdjust(string sBarCode, string sPrintName) {
            object[] results = this.Invoke("PrintBarCodeAdjust", new object[] {
                        sBarCode,
                        sPrintName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPrintBarCodeAdjust(string sBarCode, string sPrintName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PrintBarCodeAdjust", new object[] {
                        sBarCode,
                        sPrintName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndPrintBarCodeAdjust(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrintBarCodeQTY", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PrintBarCodeQTY(string sBarCode, decimal dQty, string sPrintName) {
            object[] results = this.Invoke("PrintBarCodeQTY", new object[] {
                        sBarCode,
                        dQty,
                        sPrintName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPrintBarCodeQTY(string sBarCode, decimal dQty, string sPrintName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PrintBarCodeQTY", new object[] {
                        sBarCode,
                        dQty,
                        sPrintName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndPrintBarCodeQTY(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrintBarCodeQTYSecond", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PrintBarCodeQTYSecond(string sBarCode, decimal dQty, string sPrintName) {
            object[] results = this.Invoke("PrintBarCodeQTYSecond", new object[] {
                        sBarCode,
                        dQty,
                        sPrintName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPrintBarCodeQTYSecond(string sBarCode, decimal dQty, string sPrintName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PrintBarCodeQTYSecond", new object[] {
                        sBarCode,
                        dQty,
                        sPrintName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndPrintBarCodeQTYSecond(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
