delete from SO_SODetails
delete from SO_SODetailsHistory
delete from SO_SOMain
delete from SO_SOMainHistory
delete from SO_SOOutDetails
delete from SO_SOOutDetailsHistory
delete from SO_SOOutMain
delete from SO_SOOutMainHistory
delete from SO_SOOutSublist
delete from SO_SOOutSublistHistory
delete from RdRecord
delete from RdRecordHistory
delete from RdRecords
delete from RdRecordsHistory
delete from MO_MODetails
delete from MO_MODetailsHistory
delete from MO_MOMain
delete from MO_MOMainHistory
delete from MO_MOSublist
delete from MO_MOSublistHistory
delete from PO_PODetails
delete from PO_PODetailsHistory
delete from PO_POMain
delete from PO_POMainHistory