if exists (select * from sysobjects where id = OBJECT_ID('[_UAP_Language]') and OBJECTPROPERTY(id, 'IsUserTable') = 1) 
	DROP TABLE [_UAP_Language]

CREATE TABLE [_UAP_Language] (
[cVoucher] [nvarchar]  (50) NOT NULL,
[zh-cn] [nvarchar]  (200) NOT NULL,
[en-us] [nvarchar]  (200) NULL,
[zh-tw] [nvarchar]  (200) NULL)

ALTER TABLE [_UAP_Language] WITH NOCHECK ADD  CONSTRAINT [PK__UAP_Language] PRIMARY KEY  NONCLUSTERED ( [cVoucher],[zh-cn] )
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'单据尚未审核',N'Documents not audit')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'当前期间已有数据',N'Data is available during the current period')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'登陆日期不正确',N'Incorrect login date')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'读取数据成功',N'Read data success')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'发票 - 未核销',N'Invoice - Accrued assets')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'获取单据号失败',N'Get the document number failed')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'没有数据',N'No data')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'请设置汇率',N'Please set the exchange rate')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'请设置基础档案',N'Please set the basic file')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'请设置基础档案 - 汇兑损益未实现',N'Please set the basic file (The exchange gains and losses are not realized)')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'请设置基础档案 - 汇兑损益已实现',N'Please set the basic file (The exchange gains and losses have been realized)')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'请设置凭证类别',N'Please set the credentials category')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'请设置摘要',N'Please set the summary')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'请选择单据',N'Please select documents')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'请指定年',N'Please set year')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'请指定月',N'Please set month')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'生成凭证成功',N'Generate certificate success')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'未设置本币币种',N'No local currency is set')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'已经结账',N'Settle accounts')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'已经生成凭证',N'Accounting vouchers already exist')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'已经生成凭证，不能弃审',N'Accounting vouchers already exist')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AP',N'应收单 - 未核销',N'Single receivable - Accrued assets')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'单据尚未审核',N'Documents not audit')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'当前期间已有数据',N'Data is available during the current period')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'登陆日期不正确',N'Incorrect login date')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'读取数据成功',N'Read data success')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'发票 - 未核销',N'Invoice - Accrued assets')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'获取单据号失败',N'Get the document number failed')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'没有数据',N'No data')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'请设置汇率',N'Please set the exchange rate')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'请设置基础档案',N'Please set the basic file')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'请设置基础档案 - 汇兑损益未实现',N'Please set the basic file (The exchange gains and losses are not realized)')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'请设置基础档案 - 汇兑损益已实现',N'Please set the basic file (The exchange gains and losses have been realized)')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'请设置凭证类别',N'Please set the credentials category')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'请设置摘要',N'Please set the summary')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'请选择单据',N'Please select documents')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'请指定年',N'Please set year')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'请指定月',N'Please set month')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'生成凭证成功',N'Generate certificate success')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'未设置本币币种',N'No local currency is set')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'已经结账',N'Settle accounts')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'已经生成凭证',N'Accounting vouchers already exist')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'已经生成凭证，不能弃审',N'Accounting vouchers already exist')
INSERT [_UAP_Language] ([cVoucher],[zh-cn],[en-us]) VALUES ( N'UAP_ClientPlugin_AR',N'应收单 - 未核销',N'Single receivable - Accrued assets')
