// 
// Generated by ActiveRecord Generator
// 
//
namespace PMMWS
{
    using Castle.ActiveRecord;
    using Castle.ActiveRecord.Queries;
    
    [ActiveRecord("[PMS_AT_WO]")]
    public class HPOrder : ActiveRecordBase
    {
        
        private int _orderId;

        private string _orderNo;

        private string _mST;
        
        private string _mCT;
        
        private string _faultInfo;
        
        private string _sT;
        
        private string _cT;
        
        private string _alarmCode;
        
        private string _operator;
        
        private string _machineName;
        
        private string _machineType;
        
        private string _definition;
        
        private string _olcation;
        
        private string _reason;
        
        private string _remedy;
        
        private string _partName;
        
        private string _partNO;
        
        private string _partType;
        
        private string _partPrice;
        
        private string _partWaitTime;
        
        private string _statues;
        
        private string _scanId;
        
        private string _workerId;

        private string _faultType;

        private string _orders;

        private bool _isEHS;

        [Property()]
        public bool IsEHS
        {
            get
            {
                return this._isEHS;
            }
            set
            {
                this._isEHS = value;
            }

        }

        
        [PrimaryKey(PrimaryKeyType.Native, "Order_Id")]
        public int OrderId
        {
            get
            {
                return this._orderId;
            }
            set
            {
                this._orderId = value;
            }
        }

        [Property(Column = "Order_No")]
        public string OrderNo
        {
            get
            {
                return this._orderNo;
            }
            set
            {
                this._orderNo = value;
            }
        }

        [Property()]
        public string MST
        {
            get
            {
                return this._mST;
            }
            set
            {
                this._mST = value;
            }
        }
        
        [Property()]
        public string MCT
        {
            get
            {
                return this._mCT;
            }
            set
            {
                this._mCT = value;
            }
        }
        
        [Property()]
        public string FaultInfo
        {
            get
            {
                return this._faultInfo;
            }
            set
            {
                this._faultInfo = value;
            }
        }
        
        [Property()]
        public string ST
        {
            get
            {
                return this._sT;
            }
            set
            {
                this._sT = value;
            }
        }
        
        [Property()]
        public string CT
        {
            get
            {
                return this._cT;
            }
            set
            {
                this._cT = value;
            }
        }
        
        [Property()]
        public string AlarmCode
        {
            get
            {
                return this._alarmCode;
            }
            set
            {
                this._alarmCode = value;
            }
        }
        
        [Property()]
        public string Operator
        {
            get
            {
                return this._operator;
            }
            set
            {
                this._operator = value;
            }
        }
        
        [Property(Column="Machine_Name")]
        public string MachineCode
        {
            get
            {
                return this._machineName;
            }
            set
            {
                this._machineName = value;
            }
        }
        
        [Property(Column="Machine_Type")]
        public string MachineType
        {
            get
            {
                return this._machineType;
            }
            set
            {
                this._machineType = value;
            }
        }
        
        [Property()]
        public string Definition
        {
            get
            {
                return this._definition;
            }
            set
            {
                this._definition = value;
            }
        }
        
        [Property()]
        public string Olcation
        {
            get
            {
                return this._olcation;
            }
            set
            {
                this._olcation = value;
            }
        }
        
        [Property()]
        public string Reason
        {
            get
            {
                return this._reason;
            }
            set
            {
                this._reason = value;
            }
        }
        
        [Property()]
        public string Remedy
        {
            get
            {
                return this._remedy;
            }
            set
            {
                this._remedy = value;
            }
        }
        
        [Property()]
        public string PartName
        {
            get
            {
                return this._partName;
            }
            set
            {
                this._partName = value;
            }
        }
        
        [Property()]
        public string PartNO
        {
            get
            {
                return this._partNO;
            }
            set
            {
                this._partNO = value;
            }
        }
        
        [Property()]
        public string PartType
        {
            get
            {
                return this._partType;
            }
            set
            {
                this._partType = value;
            }
        }
        
        [Property()]
        public string PartPrice
        {
            get
            {
                return this._partPrice;
            }
            set
            {
                this._partPrice = value;
            }
        }
        
        [Property()]
        public string PartWaitTime
        {
            get
            {
                return this._partWaitTime;
            }
            set
            {
                this._partWaitTime = value;
            }
        }
        
        [Property()]
        public string Statues
        {
            get
            {
                return this._statues;
            }
            set
            {
                this._statues = value;
            }
        }
        
        [Property(Column="Scan_Id")]
        public string ScanId
        {
            get
            {
                return this._scanId;
            }
            set
            {
                this._scanId = value;
            }
        }


        [Property()]
        public string FaultType
        {
            get
            {
                return this._faultType;
            }
            set
            {
                this._faultType = value;
            }
        }
 
        [Property(Column = "Worker_Id")]
        public string WorkerId
        {
            get
            {
                return this._workerId;
            }
            set
            {
                this._workerId = value;
            }
        }

        public static void DeleteAll()
        {
            ActiveRecordBase.DeleteAll(typeof(HPOrder));
        }
        
        public static HPOrder[] FindAll()
        {
            return ((HPOrder[])(ActiveRecordBase.FindAll(typeof(HPOrder))));
        }
        
        public static HPOrder Find(int OrderId)
        {
            return ((HPOrder)(ActiveRecordBase.FindByPrimaryKey(typeof(HPOrder), OrderId)));
        }

        public static HPOrder[] FindbyStatues(string statues)
        {
            SimpleQuery qe = new SimpleQuery(typeof(HPOrder), @"from HPOrder where Statues = ? ", statues);
            HPOrder[] HPOrders = (HPOrder[])ExecuteQuery(qe);
            return HPOrders;
        }


        public static HPOrder[] FindbyDateTime(string dt1, string dt2)
        {
            SimpleQuery qe = new SimpleQuery(typeof(HPOrder), @"from HPOrder where ST >= ? and  ST <= ? order by Order_Id desc", dt1, dt2);
            HPOrder[] HPOrders = (HPOrder[])ExecuteQuery(qe);
            return HPOrders;
        }


        public static HPOrder[] FindbyMachineNameAndStatues(string MachineName, string statues)
        {
            SimpleQuery qe = new SimpleQuery(typeof(HPOrder), @"from HPOrder where Statues = ? and Machine_Name = ? ", statues, MachineName);
            HPOrder[] HPOrders = (HPOrder[])ExecuteQuery(qe);
            return HPOrders;
        }

        public static string[] FindbyDistinctField(string fieldName)
        {
            SimpleQuery query = new SimpleQuery(typeof(HPOrder), typeof(string), @"select distinct hpOrder." + fieldName + " from HPOrder hpOrder");
            return (string[])ExecuteQuery(query);
        }

    
    }
}
