// 
// Generated by ActiveRecord Generator
// 
//
namespace PMMWS
{
    using Castle.ActiveRecord;
    using Castle.ActiveRecord.Queries;
    
    [ActiveRecord("[PMS_AT_PReport]")]
    public class HPPOrder : ActiveRecordBase
    {
        
        private string _pieId;
        
        private string _faultId;
        
        private decimal _stopTimeP;
        
        private decimal _mTimeP;
        
        private string _weekNum;

        private string _faultType;

        [PrimaryKey(PrimaryKeyType.Assigned, "Pie_Id")]
        public string PieId
        {
            get
            {
                return this._pieId;
            }
            set
            {
                this._pieId = value;
            }
        }
        
        [Property(Column="Fault_Id")]
        public string FaultId
        {
            get
            {
                return this._faultId;
            }
            set
            {
                this._faultId = value;
            }
        }
        
        [Property()]
        public decimal StopTimeP
        {
            get
            {
                return this._stopTimeP;
            }
            set
            {
                this._stopTimeP = value;
            }
        }
        
        [Property()]
        public decimal MTimeP
        {
            get
            {
                return this._mTimeP;
            }
            set
            {
                this._mTimeP = value;
            }
        }
        
        [Property()]
        public string WeekNum
        {
            get
            {
                return this._weekNum;
            }
            set
            {
                this._weekNum = value;
            }
        }

        [Property(Column = "Fault_Type")]
        public string FaultType
        {
            get
            {
                return this._faultType;
            }
            set
            {
                this._faultType = value;
            }
        }

        
        public static void DeleteAll()
        {
            ActiveRecordBase.DeleteAll(typeof(HPPOrder));
        }

        public static HPPOrder[] FindAll()
        {
            return ((HPPOrder[])(ActiveRecordBase.FindAll(typeof(HPPOrder))));
        }

        public static HPPOrder Find(string PieId)
        {
            try
            {
                return ((HPPOrder)(ActiveRecordBase.FindByPrimaryKey(typeof(HPPOrder), PieId)));
            }
            catch
            {
                return null;
            }
         }
        public static HPPOrder[] FindbyWeeksNum(string WeeksNum)
        {
            SimpleQuery qe = new SimpleQuery(typeof(HPPOrder), @"from HPPOrder where WeekNum = ?", WeeksNum);
            HPPOrder[] HPPOrders = (HPPOrder[])ExecuteQuery(qe);
            return HPPOrders;
        }
    }
}
