// 
// Generated by ActiveRecord Generator
// 
//
namespace PMMWS
{
    using Castle.ActiveRecord;
    using Castle.ActiveRecord.Queries;
    
    [ActiveRecord("PMS_MPlan")]
    public class PMSMPlan : ActiveRecordBase
    {
        
        private int _sPId;
        
        private string _materialCode;
        
        private string _itemDescription;
        
        private string _specification;
        
        private string _itemNO;
        
        private string _uM;
        
        private string _qty;
        
        private string _dueDate;
        
        private string _unitPrice;
        
        private string _checkingDate;
        
        private string _purpose;
        
        private string _storageStatus;
        
        private string _sPName;

        private string _safeQty;

        private string _isAlarm;
        
        [PrimaryKey(PrimaryKeyType.Native, "SP_Id")]
        public int SPId
        {
            get
            {
                return this._sPId;
            }
            set
            {
                this._sPId = value;
            }
        }
        
        [Property(Column="Material_Code")]
        public string MaterialCode
        {
            get
            {
                return this._materialCode;
            }
            set
            {
                this._materialCode = value;
            }
        }
        
        [Property(Column="Item_Description")]
        public string ItemDescription
        {
            get
            {
                return this._itemDescription;
            }
            set
            {
                this._itemDescription = value;
            }
        }
        
        [Property()]
        public string Specification
        {
            get
            {
                return this._specification;
            }
            set
            {
                this._specification = value;
            }
        }
        
        [Property(Column="Item_NO")]
        public string ItemNO
        {
            get
            {
                return this._itemNO;
            }
            set
            {
                this._itemNO = value;
            }
        }

        [Property(Column="Safe_Qty")]
        public string SafeQty
        {
            get
            {
                return this._safeQty;
            }
            set
            {
                this._safeQty = value;
            }
        }


        [Property()]
        public string UM
        {
            get
            {
                return this._uM;
            }
            set
            {
                this._uM = value;
            }
        }
        
        [Property()]
        public string Qty
        {
            get
            {
                return this._qty;
            }
            set
            {
                this._qty = value;
            }
        }
        
        [Property()]
        public string DueDate
        {
            get
            {
                return this._dueDate;
            }
            set
            {
                this._dueDate = value;
            }
        }
        
        [Property()]
        public string UnitPrice
        {
            get
            {
                return this._unitPrice;
            }
            set
            {
                this._unitPrice = value;
            }
        }
        
        [Property()]
        public string CheckingDate
        {
            get
            {
                return this._checkingDate;
            }
            set
            {
                this._checkingDate = value;
            }
        }
        
        [Property()]
        public string Purpose
        {
            get
            {
                return this._purpose;
            }
            set
            {
                this._purpose = value;
            }
        }
        
        [Property()]
        public string StorageStatus
        {
            get
            {
                return this._storageStatus;
            }
            set
            {
                this._storageStatus = value;
            }
        }


        [Property()]
        public string IsAlarm
        {
            get
            {
                return this._isAlarm;
            }
            set
            {
                this._isAlarm = value;
            }
        }


        [Property(Column="SP_Name")]
        public string SPName
        {
            get
            {
                return this._sPName;
            }
            set
            {
                this._sPName = value;
            }
        }
        
        public static void DeleteAll()
        {
            ActiveRecordBase.DeleteAll(typeof(PMSMPlan));
        }
        
        public static PMSMPlan[] FindAll()
        {
            return ((PMSMPlan[])(ActiveRecordBase.FindAll(typeof(PMSMPlan))));
        }
        
        public static PMSMPlan Find(int SPId)
        {
            return ((PMSMPlan)(ActiveRecordBase.FindByPrimaryKey(typeof(PMSMPlan), SPId)));
        }

        public static PMSMPlan[] FindbySPName(string SPName)
        {
            SimpleQuery qe = new SimpleQuery(typeof(PMSMPlan), @"from PMSMPlan where SP_Name = ? ", SPName);
            PMSMPlan[] PMSMPlans = (PMSMPlan[])ExecuteQuery(qe);
            return PMSMPlans;
        }

        public static PMSMPlan[] FindbyQty(string Qty)
        {
            SimpleQuery qe = new SimpleQuery(typeof(PMSMPlan), @"from PMSMPlan where Qty < Safe_Qty ");
            PMSMPlan[] PMSMPlans = (PMSMPlan[])ExecuteQuery(qe);
            return PMSMPlans;
        }
        public static PMSMPlan[] FindbyQtyAlarm()
        {
            SimpleQuery qe = new SimpleQuery(typeof(PMSMPlan), @"from PMSMPlan where Qty < Safe_Qty and IsAlarm Is Null ");
            PMSMPlan[] PMSMPlans = (PMSMPlan[])ExecuteQuery(qe);
            return PMSMPlans;
        }

        public static string[] FindbyDistinctQuery()
        {
            SimpleQuery query = new SimpleQuery(typeof(PMSMPlan), typeof(string), @"select distinct pmsmplan.SPName from PMSMPlan pmsmplan");
            return (string[])ExecuteQuery(query);
        }

  

    }
}
