// 
// Generated by ActiveRecord Generator
// 
//
namespace PMMWS
{
    using Castle.ActiveRecord;
    using Castle.ActiveRecord.Queries;
    
    [ActiveRecord("PMS_PMContent")]
    public class PMSPMContent : ActiveRecordBase
    {
        
        private int _pMContentId;
        
        private string _machineName;
        
        private string _year;
        
        private string _contents1;
        
        private string _contents2;
        
        private string _contents3;
        
        private string _contents4;
        
        private string _mWorker;
        
        private string _month1;
        
        private string _month2;
        
        private string _month3;
        
        private string _month4;
        
        private string _month5;
        
        private string _month6;
        
        private string _month7;
        
        private string _month8;
        
        private string _month9;
        
        private string _month10;
        
        private string _month11;
        
        private string _month12;
        
        [PrimaryKey(PrimaryKeyType.Native, "PMContent_Id")]
        public int PMContentId
        {
            get
            {
                return this._pMContentId;
            }
            set
            {
                this._pMContentId = value;
            }
        }
        
        [Property(Column="Machine_Name")]
        public string MachineName
        {
            get
            {
                return this._machineName;
            }
            set
            {
                this._machineName = value;
            }
        }
        
        [Property()]
        public string Year
        {
            get
            {
                return this._year;
            }
            set
            {
                this._year = value;
            }
        }
        
        [Property()]
        public string Contents1
        {
            get
            {
                return this._contents1;
            }
            set
            {
                this._contents1 = value;
            }
        }
        
        [Property()]
        public string Contents2
        {
            get
            {
                return this._contents2;
            }
            set
            {
                this._contents2 = value;
            }
        }
        
        [Property()]
        public string Contents3
        {
            get
            {
                return this._contents3;
            }
            set
            {
                this._contents3 = value;
            }
        }
        
        [Property()]
        public string Contents4
        {
            get
            {
                return this._contents4;
            }
            set
            {
                this._contents4 = value;
            }
        }
        
        [Property()]
        public string MWorker
        {
            get
            {
                return this._mWorker;
            }
            set
            {
                this._mWorker = value;
            }
        }
        
        [Property()]
        public string Month1
        {
            get
            {
                return this._month1;
            }
            set
            {
                this._month1 = value;
            }
        }
        
        [Property()]
        public string Month2
        {
            get
            {
                return this._month2;
            }
            set
            {
                this._month2 = value;
            }
        }
        
        [Property()]
        public string Month3
        {
            get
            {
                return this._month3;
            }
            set
            {
                this._month3 = value;
            }
        }
        
        [Property()]
        public string Month4
        {
            get
            {
                return this._month4;
            }
            set
            {
                this._month4 = value;
            }
        }
        
        [Property()]
        public string Month5
        {
            get
            {
                return this._month5;
            }
            set
            {
                this._month5 = value;
            }
        }
        
        [Property()]
        public string Month6
        {
            get
            {
                return this._month6;
            }
            set
            {
                this._month6 = value;
            }
        }
        
        [Property()]
        public string Month7
        {
            get
            {
                return this._month7;
            }
            set
            {
                this._month7 = value;
            }
        }
        
        [Property()]
        public string Month8
        {
            get
            {
                return this._month8;
            }
            set
            {
                this._month8 = value;
            }
        }
        
        [Property()]
        public string Month9
        {
            get
            {
                return this._month9;
            }
            set
            {
                this._month9 = value;
            }
        }
        
        [Property()]
        public string Month10
        {
            get
            {
                return this._month10;
            }
            set
            {
                this._month10 = value;
            }
        }
        
        [Property()]
        public string Month11
        {
            get
            {
                return this._month11;
            }
            set
            {
                this._month11 = value;
            }
        }
        
        [Property()]
        public string Month12
        {
            get
            {
                return this._month12;
            }
            set
            {
                this._month12 = value;
            }
        }
        
        public static void DeleteAll()
        {
            ActiveRecordBase.DeleteAll(typeof(PMSPMContent));
        }
        
        public static PMSPMContent[] FindAll()
        {
            return ((PMSPMContent[])(ActiveRecordBase.FindAll(typeof(PMSPMContent))));
        }
        
        public static PMSPMContent Find(int PMContentId)
        {
            return ((PMSPMContent)(ActiveRecordBase.FindByPrimaryKey(typeof(PMSPMContent), PMContentId)));
        }

        public static PMSPMContent[] FindbyYear(string Year)
        {

            SimpleQuery qe = new SimpleQuery(typeof(PMSPMContent), @"from PMSPMContent where Year = ?", Year);

            PMSPMContent[] PMSPMPlans = (PMSPMContent[])ExecuteQuery(qe);
            return PMSPMPlans;
        }

        public static PMSPMContent[] FindbyYearAndName(string Year,string Name)
        {

            SimpleQuery qe = new SimpleQuery(typeof(PMSPMContent), @"from PMSPMContent where Year = ? and Machine_Name = ?", Year,Name);
            PMSPMContent[] PMSPMPlans = (PMSPMContent[])ExecuteQuery(qe);
            return PMSPMPlans;

        }


        public static PMSPMContent[] FindbyName(string Name)
        {

            SimpleQuery qe = new SimpleQuery(typeof(PMSPMContent), @"from PMSPMContent where Machine_Name = ?", Name);
            PMSPMContent[] PMSPMPlans = (PMSPMContent[])ExecuteQuery(qe);
            return PMSPMPlans;

        }


        public static string[] FindbyDistinctField(string fieldName)
        {
            SimpleQuery query = new SimpleQuery(typeof(PMSPMContent), typeof(string), @"select distinct pContent." + fieldName + " from PMSPMContent pContent");
            return (string[])ExecuteQuery(query);
        }
    }
}
