// 
// Generated by ActiveRecord Generator
// 
//
namespace PMMWS
{
    using Castle.ActiveRecord;
    using Castle.ActiveRecord.Queries ;
    
    [ActiveRecord("PMS_PMPlan")]
    public class PMSPMPlan : ActiveRecordBase
    {
        
        private int _pMPlanId;
        
        private int _number;
        
        private string _machineName;
        
        private string _machineType;
        
        private string _equipments;
        
        private string _month1;
        
        private string _month2;
        
        private string _month3;
        
        private string _month4;
        
        private string _month5;
        
        private string _month6;
        
        private string _month7;
        
        private string _month8;
        
        private string _month9;
        
        private string _month10;
        
        private string _month11;
        
        private string _month12;
        
        private string _year;
        
        private string _divides;

        private bool  _IsDown;

        private string _worker;

        private string _duration;
        
        [PrimaryKey(PrimaryKeyType.Native, "PMPlan_Id")]
        public int PMPlanId
        {
            get
            {
                return this._pMPlanId;
            }
            set
            {
                this._pMPlanId = value;
            }
        }
        
        [Property()]
        public int Number
        {
            get
            {
                return this._number;
            }
            set
            {
                this._number = value;
            }
        }
        
        [Property(Column="Machine_Name")]
        public string MachineName
        {
            get
            {
                return this._machineName;
            }
            set
            {
                this._machineName = value;
            }
        }
        
        [Property(Column="Machine_Type")]
        public string MachineType
        {
            get
            {
                return this._machineType;
            }
            set
            {
                this._machineType = value;
            }
        }
        
        [Property()]
        public string Equipments
        {
            get
            {
                return this._equipments;
            }
            set
            {
                this._equipments = value;
            }
        }
        
        [Property()]
        public string Month1
        {
            get
            {
                return this._month1;
            }
            set
            {
                this._month1 = value;
            }
        }
        
        [Property()]
        public string Month2
        {
            get
            {
                return this._month2;
            }
            set
            {
                this._month2 = value;
            }
        }
        
        [Property()]
        public string Month3
        {
            get
            {
                return this._month3;
            }
            set
            {
                this._month3 = value;
            }
        }
        
        [Property()]
        public string Month4
        {
            get
            {
                return this._month4;
            }
            set
            {
                this._month4 = value;
            }
        }
        
        [Property()]
        public string Month5
        {
            get
            {
                return this._month5;
            }
            set
            {
                this._month5 = value;
            }
        }
        
        [Property()]
        public string Month6
        {
            get
            {
                return this._month6;
            }
            set
            {
                this._month6 = value;
            }
        }
        
        [Property()]
        public string Month7
        {
            get
            {
                return this._month7;
            }
            set
            {
                this._month7 = value;
            }
        }
        
        [Property()]
        public string Month8
        {
            get
            {
                return this._month8;
            }
            set
            {
                this._month8 = value;
            }
        }
        
        [Property()]
        public string Month9
        {
            get
            {
                return this._month9;
            }
            set
            {
                this._month9 = value;
            }
        }
        
        [Property()]
        public string Month10
        {
            get
            {
                return this._month10;
            }
            set
            {
                this._month10 = value;
            }
        }
        
        [Property()]
        public string Month11
        {
            get
            {
                return this._month11;
            }
            set
            {
                this._month11 = value;
            }
        }
        
        [Property()]
        public string Month12
        {
            get
            {
                return this._month12;
            }
            set
            {
                this._month12 = value;
            }
        }
        
        [Property()]
        public string Year
        {
            get
            {
                return this._year;
            }
            set
            {
                this._year = value;
            }
        }
        
        [Property()]
        public string Divides
        {
            get
            {
                return this._divides;
            }
            set
            {
                this._divides = value;
            }
        }

        [Property()]
        public bool IsDown
        {
            get
            {
                return this._IsDown;
            }
            set
            {
                this._IsDown = value;
            }
        }

        [Property()]
        public string Worker
        {
            get
            {
                return this._worker;
            }
            set
            {
                this._worker = value;
            }
        }

        [Property()]
        public string Duration
        {
            get
            {
                return this._duration;
            }
            set
            {
                this._duration = value;
            }
        }


        public static void DeleteAll()
        {
            ActiveRecordBase.DeleteAll(typeof(PMSPMPlan));
        }
        
        public static PMSPMPlan[] FindAll()
        {
            return ((PMSPMPlan[])(ActiveRecordBase.FindAll(typeof(PMSPMPlan))));
        }
        
        public static PMSPMPlan Find(int PMPlanId)
        {
            return ((PMSPMPlan)(ActiveRecordBase.FindByPrimaryKey(typeof(PMSPMPlan), PMPlanId)));
        }

        public static PMSPMPlan[] FindbyYear(string Year)
        {
            SimpleQuery qe = new SimpleQuery(typeof(PMSPMPlan), @"from PMSPMPlan where Year = ?", Year);
            PMSPMPlan[] PMSPMPlans = (PMSPMPlan[])ExecuteQuery(qe);
            return PMSPMPlans;
        }

        public static PMSPMPlan[] FMonth1(string Year)
        {
            SimpleQuery qe = new SimpleQuery(typeof(PMSPMPlan), @"from PMSPMPlan where Month1 != '' and Year = ?",Year);
            PMSPMPlan[] PMSPMPlans = (PMSPMPlan[])ExecuteQuery(qe);
            return PMSPMPlans;
        }
        public static PMSPMPlan[] FMonth2(string Year)
        {
            SimpleQuery qe = new SimpleQuery(typeof(PMSPMPlan), @"from PMSPMPlan where Month2 != '' and Year= ?", Year);
            PMSPMPlan[] PMSPMPlans = (PMSPMPlan[])ExecuteQuery(qe);
            return PMSPMPlans;
        }
        public static PMSPMPlan[] FMonth3(string Year)
        {
            SimpleQuery qe = new SimpleQuery(typeof(PMSPMPlan), @"from PMSPMPlan where Month3 != '' and Year=?", Year);
            PMSPMPlan[] PMSPMPlans = (PMSPMPlan[])ExecuteQuery(qe);
            return PMSPMPlans;
        }
        public static PMSPMPlan[] FMonth4(string Year)
        {
            SimpleQuery qe = new SimpleQuery(typeof(PMSPMPlan), @"from PMSPMPlan where Month4 != '' and Year=?", Year);
            PMSPMPlan[] PMSPMPlans = (PMSPMPlan[])ExecuteQuery(qe);
            return PMSPMPlans;
        }
        public static PMSPMPlan[] FMonth5(string Year)
        {
            SimpleQuery qe = new SimpleQuery(typeof(PMSPMPlan), @"from PMSPMPlan where Month5 != '' and Year=?", Year);
            PMSPMPlan[] PMSPMPlans = (PMSPMPlan[])ExecuteQuery(qe);
            return PMSPMPlans;
        }
        public static PMSPMPlan[] FMonth6(string Year)
        {
            SimpleQuery qe = new SimpleQuery(typeof(PMSPMPlan), @"from PMSPMPlan where Month6 != '' and Year=?", Year);
            PMSPMPlan[] PMSPMPlans = (PMSPMPlan[])ExecuteQuery(qe);
            return PMSPMPlans;
        }
        public static PMSPMPlan[] FMonth7(string Year)
        {
            SimpleQuery qe = new SimpleQuery(typeof(PMSPMPlan), @"from PMSPMPlan where Month7 != '' and Year=?", Year);
            PMSPMPlan[] PMSPMPlans = (PMSPMPlan[])ExecuteQuery(qe);
            return PMSPMPlans;
        }
        public static PMSPMPlan[] FMonth8(string Year)
        {
            SimpleQuery qe = new SimpleQuery(typeof(PMSPMPlan), @"from PMSPMPlan where Month8 != '' and Year=?", Year);
            PMSPMPlan[] PMSPMPlans = (PMSPMPlan[])ExecuteQuery(qe);
            return PMSPMPlans;
        }
        public static PMSPMPlan[] FMonth9(string Year)
        {
            SimpleQuery qe = new SimpleQuery(typeof(PMSPMPlan), @"from PMSPMPlan where Month9 != '' and Year=?", Year);
            PMSPMPlan[] PMSPMPlans = (PMSPMPlan[])ExecuteQuery(qe);
            return PMSPMPlans;
        }
        public static PMSPMPlan[] FMonth10(string Year)
        {
            SimpleQuery qe = new SimpleQuery(typeof(PMSPMPlan), @"from PMSPMPlan where Month10 != '' and Year=?", Year);
            PMSPMPlan[] PMSPMPlans = (PMSPMPlan[])ExecuteQuery(qe);
            return PMSPMPlans;
        }
        public static PMSPMPlan[] FMonth11(string Year)
        {
            SimpleQuery qe = new SimpleQuery(typeof(PMSPMPlan), @"from PMSPMPlan where Month11 != '' and Year=?", Year);
            PMSPMPlan[] PMSPMPlans = (PMSPMPlan[])ExecuteQuery(qe);
            return PMSPMPlans;
        }
        public static PMSPMPlan[] FMonth12(string Year)
        {
            SimpleQuery qe = new SimpleQuery(typeof(PMSPMPlan), @"from PMSPMPlan where Month12 != '' and Year=?", Year);
            PMSPMPlan[] PMSPMPlans = (PMSPMPlan[])ExecuteQuery(qe);
            return PMSPMPlans;
        }


        public static PMSPMPlan[] FindMonthAndIsDown(int Month,string Year)
        {
            SimpleQuery qe = new SimpleQuery(typeof(PMSPMPlan), @"from PMSPMPlan where Month" + Month.ToString() + " != ''and ( IsDown is null OR IsDown = 0) and Year= ?", Year);
            PMSPMPlan[] PMSPMPlans = (PMSPMPlan[])ExecuteQuery(qe);
            return PMSPMPlans;
        }
    }
}
