// 
// Generated by ActiveRecord Generator
// 
//
namespace PMMWS
{
    using Castle.ActiveRecord;
    using Castle.ActiveRecord.Queries;

    [ActiveRecord("[PMS_Scanning]")]
    public class Scanning : ActiveRecordBase
    {
        private string _scanId;

        private string _machineName;
        
        private string _machineType;
        
        private string _sT;
        
        private string _cT;
        
        private string _faultInfo;
        
        private string _alarmCode;

        private string _statues;
               
        [PrimaryKey(PrimaryKeyType.Assigned, "Scan_Id")]
        public string ScanId
        {
            get
            {
                return this._scanId;
            }
            set
            {
                this._scanId = value;
            }
        }
        
        [Property()]
        public string MachineName
        {
            get
            {
                return this._machineName;
            }
            set
            {
                this._machineName = value;
            }
        }
        
        [Property()]
        public string MachineType
        {
            get
            {
                return this._machineType;
            }
            set
            {
                this._machineType = value;
            }
        }
        
        [Property()]
        public string ST
        {
            get
            {
                return this._sT;
            }
            set
            {
                this._sT = value;
            }
        }
        
        [Property()]
        public string CT
        {
            get
            {
                return this._cT;
            }
            set
            {
                this._cT = value;
            }
        }
        
        [Property()]
        public string FaultInfo
        {
            get
            {
                return this._faultInfo;
            }
            set
            {
                this._faultInfo = value;
            }
        }

        [Property()]
        public string AlarmCode
        {
            get
            {
                return this._alarmCode;
            }
            set
            {
                this._alarmCode = value;
            }
        }

        [Property()]
        public string Statues
        {
            get
            {
                return this._statues;
            }
            set
            {
                this._statues = value;
            }
        }

        public static Scanning Find(string ScanId)
        {
            return ((Scanning)(Scanning.FindByPrimaryKey(typeof(Scanning), ScanId)));
        }


        public static void DeleteAll()
        {
            ActiveRecordBase.DeleteAll(typeof(Scanning));
        }
        
        public static Scanning[] FindAll()
        {
            return ((Scanning[])(ActiveRecordBase.FindAll(typeof(Scanning))));
        }

        public static Scanning[] FindbyStatues(string Statues)
        {

            SimpleQuery qe = new SimpleQuery(typeof(Scanning), @"from Scanning where Statues = ?", Statues);

            Scanning[] Scannings = (Scanning[])ExecuteQuery(qe);
            return Scannings;
        }

    }
}
