// 
// Generated by ActiveRecord Generator
// 
//
namespace PMMWS
{
    using Castle.ActiveRecord;
    using Castle.ActiveRecord.Queries;
    
    [ActiveRecord("[PMS_SM_Report]")]
    public class SMReport : ActiveRecordBase
    {
        
        private int _reportId;
        
        private string _machineName;
        
        private string _machineType;
        
        private string _sT;
        
        private string _cT;
        
        private string _mST;
        
        private string _mCT;
        
        private string _weekNum;
        
        private string _faultInfo;
        
        private string _scanId;
        
        private decimal _stopTime;
        
        private decimal _mTime;

        private decimal _rate;

        private string _IsTotal;

        private string _weeks;

        private string _faultType;

        private string _year;

        private int _orders;

        private int _week;
        
        [PrimaryKey(PrimaryKeyType.Native, "Report_Id")]
        public int ReportId
        {
            get
            {
                return this._reportId;
            }
            set
            {
                this._reportId = value;
            }
        }
        
        [Property(Column="Machine_Name")]
        public string MachineName
        {
            get
            {
                return this._machineName;
            }
            set
            {
                this._machineName = value;
            }
        }
        
        [Property(Column="Machine_Type")]
        public string MachineType
        {
            get
            {
                return this._machineType;
            }
            set
            {
                this._machineType = value;
            }
        }
        
        [Property()]
        public string ST
        {
            get
            {
                return this._sT;
            }
            set
            {
                this._sT = value;
            }
        }
        
        [Property()]
        public string CT
        {
            get
            {
                return this._cT;
            }
            set
            {
                this._cT = value;
            }
        }
        
        [Property()]
        public string MST
        {
            get
            {
                return this._mST;
            }
            set
            {
                this._mST = value;
            }
        }
        
        [Property()]
        public string MCT
        {
            get
            {
                return this._mCT;
            }
            set
            {
                this._mCT = value;
            }
        }
        
        [Property()]
        public string WeekNum
        {
            get
            {
                return this._weekNum;
            }
            set
            {
                this._weekNum = value;
            }
        }
        
        [Property(Column="Fault_Info")]
        public string FaultInfo
        {
            get
            {
                return this._faultInfo;
            }
            set
            {
                this._faultInfo = value;
            }
        }
        
        [Property(Column="Scan_Id")]
        public string ScanId
        {
            get
            {
                return this._scanId;
            }
            set
            {
                this._scanId = value;
            }
        }
        
        [Property()]
        public decimal StopTime
        {
            get
            {
                return this._stopTime;
            }
            set
            {
                this._stopTime = value;
            }
        }
        
        [Property()]
        public decimal MTime
        {
            get
            {
                return this._mTime;
            }
            set
            {
                this._mTime = value;
            }
        }

        [Property()]
        public decimal Rate
        {
            get
            {
                return this._rate;
            }
            set
            {
                this._rate = value;
            }
        }

        [Property()]
        public string IsTotal
        {
            get
            {
                return this._IsTotal;
            }
            set
            {
                this._IsTotal = value;
            }
        }

        [Property()]
        public string Weeks
        {
            get
            {
                return this._weeks;
            }
            set
            {
                this._weeks = value;
            }
        }

        [Property()]
        public string FaultType
        {
            get
            {
                return this._faultType;
            }
            set
            {
                this._faultType = value;
            }
        }

        [Property()]
        public string Year
        {
            get
            {
                return this._year;
            }
            set
            {
                this._year = value;
            }
        }

        [Property()]
        public int Orders
        {
            get
            {
                return this._orders;
            }
            set
            {
                this._orders = value;
            }
        }
        [Property()]
        public int Week
        {
            get
            {
                return this._week;
            }
            set
            {
                this._week = value;
            }
        }
        public static void DeleteAll()
        {
            ActiveRecordBase.DeleteAll(typeof(SMReport));
        }
        
        public static SMReport[] FindAll()
        {
            return ((SMReport[])(ActiveRecordBase.FindAll(typeof(SMReport))));
        }
        
        public static SMReport Find(int ReportId)
        {
            return ((SMReport)(ActiveRecordBase.FindByPrimaryKey(typeof(SMReport), ReportId)));
        }
        public static SMReport[] FindbyScanId(string ScanId)
        {
            SimpleQuery qe = new SimpleQuery(typeof(SMReport), @"from SMReport where Scan_Id = ? ", ScanId);
            SMReport[] SMReports = (SMReport[])ExecuteQuery(qe);
            return SMReports;
        }

        public static SMReport[] FindbyTotalandYear(string Total, string Year)
        {
            SimpleQuery qe = new SimpleQuery(typeof(SMReport), @"from SMReport where IsTotal =? and Year =? order by Week", Total, Year);
            SMReport[] SMReports = (SMReport[])ExecuteQuery(qe);
            return SMReports;
        }


        public static SMReport[] FindbyWeeksNum(string WeeksNum)
        {
            SimpleQuery qe = new SimpleQuery(typeof(SMReport), @"from SMReport where WeekNum = ?", WeeksNum);
            SMReport[] SMReports = (SMReport[])ExecuteQuery(qe);
            return SMReports;
        }


        public static SMReport[] FindbyWeeksNumAndFaultInfo(string WeeksNum, string FaultInfo)
        {
            try
            {
                SimpleQuery qe = new SimpleQuery(typeof(SMReport), @"from SMReport where WeekNum = ? and Fault_Info =?", WeeksNum, FaultInfo);
                SMReport[] SMReports = (SMReport[])ExecuteQuery(qe);
                return SMReports;
            }
            catch
            {
                return null;
            }
        }

        public static SMReport[] FindbyWeeksNumAndFaultType(string WeeksNum, string FaultType)
        {
            try
            {
                SimpleQuery qe = new SimpleQuery(typeof(SMReport), @"from SMReport where WeekNum = ? and FaultType =?", WeeksNum, FaultType);
                SMReport[] SMReports = (SMReport[])ExecuteQuery(qe);
                return SMReports;
            }
            catch
            {
                return null;
            }
        }

        public static SMReport[] FindbyWeeksNumAndTotal(string WeeksNum, string Total,string FaultType)
        {
            SimpleQuery qe = new SimpleQuery(typeof(SMReport), @"from SMReport where WeekNum = ? and IsTotal =? and (FaultType is null or FaultType != ? ) order by Orders", WeeksNum,Total,FaultType);
            SMReport[] SMReports = (SMReport[])ExecuteQuery(qe);
            return SMReports;
        }

        public static SMReport[] FindbyWeeksNumAndTotalAndOrders(string WeeksNum, string Total,int orders)
        {
            SimpleQuery qe = new SimpleQuery(typeof(SMReport), @"from SMReport where WeekNum = ? and IsTotal =? and Orders =?",WeeksNum,Total,orders);
            SMReport[] SMReports = (SMReport[])ExecuteQuery(qe);
            return SMReports;
        }


        public static SMReport[] FindbyTotal(string Total)
        {
            SimpleQuery qe = new SimpleQuery(typeof(SMReport), @"from SMReport where IsTotal =? order by Week", Total);
            SMReport[] SMReports = (SMReport[])ExecuteQuery(qe);
            return SMReports;
        }


        public static string[] FindbyDistinctQuery(string WeekNum)
        {

            SimpleQuery query = new SimpleQuery(typeof(SMReport), typeof(string), @"select distinct mareport.FaultType from SMReport mareport where WeekNum = ?", WeekNum);

            return (string[])ExecuteQuery(query);
        }

        public static SMReport[] FindbyTotalandLastYear(string Total, string Year)
        {
            SimpleQuery qe = new SimpleQuery(typeof(SMReport), @"from SMReport where IsTotal =? and Year >=? order by Week", Total, Year);
            SMReport[] MAReports = (SMReport[])ExecuteQuery(qe);
            return MAReports;
        }
    }

}
