USE [UFDATA_001_2015]
GO

/****** Object:  Table [dbo].[_IP]    Script Date: 2015-09-13 20:50:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[_IP](
	[IP] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK__IP] PRIMARY KEY CLUSTERED 
(
	[IP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


insert into _IP values('10.131.64.237')
