//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Test.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DBWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class DBWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UpdateSO_ScanStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePO_ScanStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback Add_DispatchListOperationCompleted;
        
        private System.Threading.SendOrPostCallback Add_Rdrecord01OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DBWebService() {
            this.Url = global::Test.Properties.Settings.Default.系统服务_WebReference_DBWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UpdateSO_ScanStatusCompletedEventHandler UpdateSO_ScanStatusCompleted;
        
        /// <remarks/>
        public event UpdatePO_ScanStatusCompletedEventHandler UpdatePO_ScanStatusCompleted;
        
        /// <remarks/>
        public event Add_DispatchListCompletedEventHandler Add_DispatchListCompleted;
        
        /// <remarks/>
        public event Add_Rdrecord01CompletedEventHandler Add_Rdrecord01Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateSO_ScanStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateSO_ScanStatus(string sSOCodeStatus) {
            object[] results = this.Invoke("UpdateSO_ScanStatus", new object[] {
                        sSOCodeStatus});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSO_ScanStatusAsync(string sSOCodeStatus) {
            this.UpdateSO_ScanStatusAsync(sSOCodeStatus, null);
        }
        
        /// <remarks/>
        public void UpdateSO_ScanStatusAsync(string sSOCodeStatus, object userState) {
            if ((this.UpdateSO_ScanStatusOperationCompleted == null)) {
                this.UpdateSO_ScanStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSO_ScanStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateSO_ScanStatus", new object[] {
                        sSOCodeStatus}, this.UpdateSO_ScanStatusOperationCompleted, userState);
        }
        
        private void OnUpdateSO_ScanStatusOperationCompleted(object arg) {
            if ((this.UpdateSO_ScanStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSO_ScanStatusCompleted(this, new UpdateSO_ScanStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdatePO_ScanStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdatePO_ScanStatus(string sPOCodeStatus) {
            object[] results = this.Invoke("UpdatePO_ScanStatus", new object[] {
                        sPOCodeStatus});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePO_ScanStatusAsync(string sPOCodeStatus) {
            this.UpdatePO_ScanStatusAsync(sPOCodeStatus, null);
        }
        
        /// <remarks/>
        public void UpdatePO_ScanStatusAsync(string sPOCodeStatus, object userState) {
            if ((this.UpdatePO_ScanStatusOperationCompleted == null)) {
                this.UpdatePO_ScanStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePO_ScanStatusOperationCompleted);
            }
            this.InvokeAsync("UpdatePO_ScanStatus", new object[] {
                        sPOCodeStatus}, this.UpdatePO_ScanStatusOperationCompleted, userState);
        }
        
        private void OnUpdatePO_ScanStatusOperationCompleted(object arg) {
            if ((this.UpdatePO_ScanStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePO_ScanStatusCompleted(this, new UpdatePO_ScanStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Add_DispatchList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Add_DispatchList(string sdt) {
            object[] results = this.Invoke("Add_DispatchList", new object[] {
                        sdt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Add_DispatchListAsync(string sdt) {
            this.Add_DispatchListAsync(sdt, null);
        }
        
        /// <remarks/>
        public void Add_DispatchListAsync(string sdt, object userState) {
            if ((this.Add_DispatchListOperationCompleted == null)) {
                this.Add_DispatchListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdd_DispatchListOperationCompleted);
            }
            this.InvokeAsync("Add_DispatchList", new object[] {
                        sdt}, this.Add_DispatchListOperationCompleted, userState);
        }
        
        private void OnAdd_DispatchListOperationCompleted(object arg) {
            if ((this.Add_DispatchListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Add_DispatchListCompleted(this, new Add_DispatchListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Add_Rdrecord01", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Add_Rdrecord01(string sdt) {
            object[] results = this.Invoke("Add_Rdrecord01", new object[] {
                        sdt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Add_Rdrecord01Async(string sdt) {
            this.Add_Rdrecord01Async(sdt, null);
        }
        
        /// <remarks/>
        public void Add_Rdrecord01Async(string sdt, object userState) {
            if ((this.Add_Rdrecord01OperationCompleted == null)) {
                this.Add_Rdrecord01OperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdd_Rdrecord01OperationCompleted);
            }
            this.InvokeAsync("Add_Rdrecord01", new object[] {
                        sdt}, this.Add_Rdrecord01OperationCompleted, userState);
        }
        
        private void OnAdd_Rdrecord01OperationCompleted(object arg) {
            if ((this.Add_Rdrecord01Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Add_Rdrecord01Completed(this, new Add_Rdrecord01CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateSO_ScanStatusCompletedEventHandler(object sender, UpdateSO_ScanStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSO_ScanStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSO_ScanStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdatePO_ScanStatusCompletedEventHandler(object sender, UpdatePO_ScanStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePO_ScanStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePO_ScanStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Add_DispatchListCompletedEventHandler(object sender, Add_DispatchListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Add_DispatchListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Add_DispatchListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void Add_Rdrecord01CompletedEventHandler(object sender, Add_Rdrecord01CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Add_Rdrecord01CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Add_Rdrecord01CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591