
/////////////////////////////////////////////////////下拉列表
function GetDropDownListValue(obj) {
   var ddl = window.document.getElementById(obj);
   var ivalue = "";
   for (var i = 0; i < ddl.length; i++) {
       if (ddl.options[i].selected == true) {
           ivalue = ddl.options[i].value;
       }
   }
   return ivalue;
}

function SetDropDownListValue(obj,value) {
   var ddl = window.document.getElementById(obj);
   for (var i = 0; i < ddl.length; i++) {
       if (ddl.options[i].value == value) {
           ddl.options[i].selected = true;
       }
   }
   return true;
}

function BindDropDownList(obj, dtable, iid, name) {
    var ddl = window.document.getElementById(obj);
    for (var i = ddl.length - 1; i >= 0; i--) {
        ddl.remove(i);
    }
    if (dtable != null && typeof (dtable) == "object") {
        for (var q = 0; q < dtable.Rows.length; q++) {
            ddl.options.add(new Option(dtable.Rows[q][name], dtable.Rows[q][iid]));
        }
    }
    return true;
}
/////////////////////////////////////////////////////子表


////////////////////////////////////////////////////

function GetDefaultImg() {
    return "R0lGODlhQgBgAPcAAC49TaWttUxbadnf43uEjcTM0EJPXGJteI6ZojlIVba + xOTp7NHY3Gt4g1ZhbYeSnD9MWt7l55ykrEpWZLzDyKuyuMvR1XF9iVNgbDpKWmhzfjdFVNbc336Jk0JRYVtodebs7r / GzKGpsN7m71FdajJCUUpXY8fO03F7hrK5vs3U2EJKY4SMlXWBjNPY3IyWnWBrdmVxe9zh5ZOdpXyHklRicGp2g1plcZehp729xcLJza2tta61vDFCSv///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAQgBgAAAI/wAjCBxIsKDBgxEWKCS4AKHDhxAjEuTAQIYLBRI6NDgQg0AADg0lihx5cAAFHBMmQCgBAECJlywnSJBBsqZIDjNuQEiQoWdPD0CDZkhAYIDNowhFYACQwEDQp1CBlmghIwUCCyGRkmTQYcMGp1HDBk0QY6UDBCq0jrTwoQRYsXA9/MxQAoVRtRBDYEgQt2/UDS3u4i14IsIJEhv8Kn66AQWDwQVnOJiQYbFloBscFIYsUMHPy5c3aODAuQCJyqBTU4Ds4kDi1KAhYHghGKmG17BBZwAAIy1SHG5z54aAICvJChAgCBeu4bFNCTMELM+9wQbpmidsoJ4Ou0JNBiT4cv/PHcA4RBkXcI/X7WDkAhzq16e2MPLBW/mgCfiOuCAFftgZ2GCeQyC0IN5/l01Ak0QMyIWgbptFxEN8D/q1gQIi0bBdhYptEIBIL2zIYV8JSCDSDCKOCFcGOIh0gXIq+pVAixFxEEOMiiUgAoM34CgjhjV+4GNfENAn0QwwDhmWAAtGNAAMKSqZQQMDIgRCB1EOmYEEVR4EggRZ+jiBDiTpMIGSUGWAQpMSDaAdmkKVV5MCcAYlAANdOlTAB0miCcNqI1FgQJgxlkBDngWBMAOFUrKAKEM4EBojBCIswOZDFJxZJ1ACRChSC31K2YJNOtynJAQKPGrQAg1IWuEHl4r/lGmdXCLVgqv/YWDkUQWgmcELeL2oZAh4haBpjBlcABkLuHKHAbGDnUBZs7nNUABnEYhwwQemrpdBDddhG0GkD2bwgKo2WSBAqOONKe5AC2D5XwY0yBArZBbU0O1yE+z6rkAisCucuehqtQAC+8L2gXP/TtQqdxlU2rBBnk337cQlCUCtWDNYijFDGmwclQBkfkzQlSJD9QEH9za8QIjLNTBAbR8fnLJQF7TsMgI3B2XDzCYPhPJyGOwXNAgx9BwUDx4HrYIBCS+WAQwFD4YAo6BtQGPNyAmc2gYsDFB1TRyI4OB4EGxwAJCcNUQBCySUoLRYXl0AKF4WSABD2p/9a5c2BBcoQLNEIFRFgAclbOA1fnSRVQEHIIh0wgs3eLV4hTslQAICJR+0AAcVNGBA4lHjmIBbKDyelUksmODV3H4nkIAJNCgAUllyw85h4ze8oPimqZ0O/PDEF2/88cgnr/zyzDfv/PPQ+xUQADsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";
}

//身份证
function IsCardno(obj) {
    var txt = document.getElementById(obj).value.toUpperCase();
    if (!(/(^\d{15}$)|(^\d{17}([0-9]|X)$)/.test(txt))) {
        alert(Ajax.AjaxMethod.GetAlert(6).value);
        document.getElementById(obj).focus();
        return false;
    }
    return true;
}
//电话号码
function IsPhone(obj) {
    var txt = document.getElementById(obj).value.toUpperCase();
    if (!(/^1[3,5]\d{9}$/).test(txt) && !(/^0(([1-9]\d)|([3-9]\d{2}))\d{8}$/).test(txt)) {
        alert(Ajax.AjaxMethod.GetAlert(10).value);
        document.getElementById(obj).focus();
        return false;
    }
    return true;
}
//是否是数字
function IsNumber(obj) {
    var txt = document.getElementById(obj).value.toUpperCase();
    if (!(/^[0-9]*[1-9][0-9]*$/).test(txt)) {
        return false;
    }
    return true;
}
//是否为空
function IsEmpty(obj, lbl) {
    var txt = document.getElementById(obj);
    if (txt.value == "") {
        alert(lbl + " " + Ajax.AjaxMethod.GetAlert(1).value);
        txt.focus();
        return false;
    }
    return true;
}

//是否包含字符串
function HasChar(obj, lbl, ichar) {
    var txt = document.getElementById(obj);
    if (txt.value.indexOf(ichar) >= 0) {
        alert(lbl + " " + Ajax.AjaxMethod.GetAlert(22).value + "'" + ichar + "'");
        txt.focus();
        return false;
    }
    return true;
}


function StartDropDownList(obj, sid) {
    alert(sid.value);
    for (var i = 0; i < obj.length; i++) {
        if (obj.options[i].value == sid.value) {
            obj[i].selected = true;
        }
    }
}
function ChangeDropDownList(obj, sid) {
    for (var i = 0; i < obj.length; i++) {
        if (obj[i].selected == true) {
            sid.value = obj.options[i].value;
        }
    }
}


function SelectDate(obj) {
    $(obj).datetimepicker({
        language: 'zh-CN',
        format: 'yyyy-mm-dd',
        minView: '2',
        todayBtn: true,
        autoclose: true,
        todayHighlight: true,
        startDate: '2000-1-1',
        forceParse: false
    });
}

