//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8935
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.8935 版自动生成。
// 
namespace MobileBaseDLL.WebServerBarCode {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DBWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class DBWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public DBWebService() {
            this.Url = "http://192.168.30.221/webJR/DBService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/b登陆", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool b登陆(string sUid, string sPwd) {
            object[] results = this.Invoke("b登陆", new object[] {
                        sUid,
                        sPwd});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginb登陆(string sUid, string sPwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("b登陆", new object[] {
                        sUid,
                        sPwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool Endb登陆(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/s登陆", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string s登陆(string sUid) {
            object[] results = this.Invoke("s登陆", new object[] {
                        sUid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begins登陆(string sUid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("s登陆", new object[] {
                        sUid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Ends登陆(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dtm当前服务器时间", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime dtm当前服务器时间() {
            object[] results = this.Invoke("dtm当前服务器时间", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindtm当前服务器时间(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dtm当前服务器时间", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.DateTime Enddtm当前服务器时间(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dtInventory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dtInventory(string cInvCode) {
            object[] results = this.Invoke("dtInventory", new object[] {
                        cInvCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindtInventory(string cInvCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dtInventory", new object[] {
                        cInvCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EnddtInventory(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sDoor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sDoor(string iPF, string iPlace) {
            object[] results = this.Invoke("sDoor", new object[] {
                        iPF,
                        iPlace});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsDoor(string iPF, string iPlace, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sDoor", new object[] {
                        iPF,
                        iPlace}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsDoor(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Save现品票登记", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Save现品票登记(System.Data.DataTable dt) {
            object[] results = this.Invoke("Save现品票登记", new object[] {
                        dt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSave现品票登记(System.Data.DataTable dt, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Save现品票登记", new object[] {
                        dt}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSave现品票登记(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt发货计划", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt发货计划(string sBarCode, string sQRCode, string iUsedAutoID) {
            object[] results = this.Invoke("dt发货计划", new object[] {
                        sBarCode,
                        sQRCode,
                        iUsedAutoID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindt发货计划(string sBarCode, string sQRCode, string iUsedAutoID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dt发货计划", new object[] {
                        sBarCode,
                        sQRCode,
                        iUsedAutoID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddt发货计划(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/chk发货计划", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string chk发货计划(string sBarCode) {
            object[] results = this.Invoke("chk发货计划", new object[] {
                        sBarCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginchk发货计划(string sBarCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("chk发货计划", new object[] {
                        sBarCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endchk发货计划(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Save出库单", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Save出库单(System.Data.DataTable dt) {
            object[] results = this.Invoke("Save出库单", new object[] {
                        dt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSave出库单(System.Data.DataTable dt, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Save出库单", new object[] {
                        dt}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSave出库单(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
