//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.5485 版自动生成。
// 
namespace TH.Smart.WebService.WebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsBarCodeSoap", Namespace="http://tempuri.org/")]
    public partial class WsBarCode : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WsBarCode() {
            this.Url = "http://192.168.150.1/webTTJM/DBScanForCheck.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sServerTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sServerTime() {
            object[] results = this.Invoke("sServerTime", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsServerTime(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sServerTime", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsServerTime(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sLogin(string sUid, string sPwd) {
            object[] results = this.Invoke("sLogin", new object[] {
                        sUid,
                        sPwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsLogin(string sUid, string sPwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sLogin", new object[] {
                        sUid,
                        sPwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsLogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sUpdatePwd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sUpdatePwd(string sUid, string sPwd, string sOldPwd) {
            object[] results = this.Invoke("sUpdatePwd", new object[] {
                        sUid,
                        sPwd,
                        sOldPwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsUpdatePwd(string sUid, string sPwd, string sOldPwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sUpdatePwd", new object[] {
                        sUid,
                        sPwd,
                        sOldPwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsUpdatePwd(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sSave工序流转", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sSave工序流转(System.Data.DataTable dtBarCode, string sUid, string sUfName) {
            object[] results = this.Invoke("sSave工序流转", new object[] {
                        dtBarCode,
                        sUid,
                        sUfName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsSave工序流转(System.Data.DataTable dtBarCode, string sUid, string sUfName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sSave工序流转", new object[] {
                        dtBarCode,
                        sUid,
                        sUfName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsSave工序流转(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sSaveRD产品入库", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sSaveRD产品入库(System.Data.DataTable dtBarCode, string sUid, string sUfNAme) {
            object[] results = this.Invoke("sSaveRD产品入库", new object[] {
                        dtBarCode,
                        sUid,
                        sUfNAme});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsSaveRD产品入库(System.Data.DataTable dtBarCode, string sUid, string sUfNAme, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sSaveRD产品入库", new object[] {
                        dtBarCode,
                        sUid,
                        sUfNAme}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsSaveRD产品入库(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/s生产订单产品工序", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string s生产订单产品工序(string sWorkIDs) {
            object[] results = this.Invoke("s生产订单产品工序", new object[] {
                        sWorkIDs});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begins生产订单产品工序(string sWorkIDs, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("s生产订单产品工序", new object[] {
                        sWorkIDs}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Ends生产订单产品工序(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/s标准工序", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string s标准工序() {
            object[] results = this.Invoke("s标准工序", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begins标准工序(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("s标准工序", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string Ends标准工序(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dtGetBarCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dtGetBarCode(string sBarCode, string sUfName) {
            object[] results = this.Invoke("dtGetBarCode", new object[] {
                        sBarCode,
                        sUfName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindtGetBarCode(string sBarCode, string sUfName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dtGetBarCode", new object[] {
                        sBarCode,
                        sUfName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EnddtGetBarCode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dtBarCode执行统计", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dtBarCode执行统计(string sBarCode, string sUfName) {
            object[] results = this.Invoke("dtBarCode执行统计", new object[] {
                        sBarCode,
                        sUfName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindtBarCode执行统计(string sBarCode, string sUfName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dtBarCode执行统计", new object[] {
                        sBarCode,
                        sUfName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EnddtBarCode执行统计(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dtWorkIDs执行统计", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dtWorkIDs执行统计(string lWorkIDs, string sUfName) {
            object[] results = this.Invoke("dtWorkIDs执行统计", new object[] {
                        lWorkIDs,
                        sUfName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindtWorkIDs执行统计(string lWorkIDs, string sUfName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dtWorkIDs执行统计", new object[] {
                        lWorkIDs,
                        sUfName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EnddtWorkIDs执行统计(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dt帐套", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dt帐套() {
            object[] results = this.Invoke("dt帐套", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindt帐套(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dt帐套", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddt帐套(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dtWareHouse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dtWareHouse(string sUfName) {
            object[] results = this.Invoke("dtWareHouse", new object[] {
                        sUfName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindtWareHouse(string sUfName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dtWareHouse", new object[] {
                        sUfName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EnddtWareHouse(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dtrd_style", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dtrd_style(string sUfName) {
            object[] results = this.Invoke("dtrd_style", new object[] {
                        sUfName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindtrd_style(string sUfName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dtrd_style", new object[] {
                        sUfName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddtrd_style(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
